### ISSUE TITLE
Are all negative methods based on a trained KGC model?

### ISSUE THREAD

**Issue by maoulee** [Fantabulous-J/Improved-Negative-Search-for-KGC#1]
Nice work for KGC tasks! I have some question about some details of your papers:
(1) All negative methods are based on a trained KGC model? Or only partial methods?
(2) Have you test your methods on the original bert models?

**Comment by Fantabulous-J** [comment]
Thanks for your interest in our paper.

1. As mentioned in the paper, only the neural negatives are sampled from a trained KGC model.
2. I am not sure if I understand your question correctly. We first train a KGC model (initialised from Bert) only using in-batch negatives, then hard negatives are sampled from its top-k predictions for each training example. We train another KGC model (also initialised from Bert) similarly, but the difference is that each training example will be paired with several hard negatives, and the hard negatives of all training examples in a mini-batch will be used as in-batch negatives for efficient training.

**Comment by maoulee** [comment]
I'm sorry for the confusion caused by my question. I would like to know which of the negative sampling methods shown in Table 2 are those that use trained models to obtain hard negative samples. What is the difference between sparse and head-relation methods

> Thanks for your interest in our paper.
> 
> 1. As mentioned in the paper, only the neural negatives are sampled from a trained KGC model.
> 2. I am not sure if I understand your question correctly. We first train a KGC model (initialised from Bert) only using in-batch negatives, then hard negatives are sampled from its top-k predictions for each training example. We train another KGC model (also initialised from Bert) similarly, but the difference is that each training example will be paired with several hard negatives, and the hard negatives of all training examples in a mini-batch will be used as in-batch negatives for efficient training.

**Comment by Fantabulous-J** [comment]
Sparse and structure-aware negatives do not use trained models to obtain hard negatives. You can find their difference in Section 3.2 of the paper.

**Comment by maoulee** [comment]
Thanks your reply ！
> Sparse and structure-aware negatives do not use trained models to obtain hard negatives. You can find their difference in Section 3.2 of the paper.

**Comment by YongqingQI** [comment]
> Thanks your reply ！
> 
> > Sparse and structure-aware negatives do not use trained models to obtain hard negatives. You can find their difference in Section 3.2 of the paper.
can you run this code successfully?
